### ISSUE TITLE
Stack imbalance when reading single image

### ISSUE THREAD

**Issue by AB-Kent** [s-u/tiff#10]
Reading just the first image from a multi-image TIFF file with
`tiff::readTIFF(path, native=TRUE, all=1)`
gives the warning
`Warning: stack imbalance in '=', 2 then 3`

Here is code to trigger the warning:
```r
path = tempfile(fileext='.tiff')
download.file('https://github.com/akoyabio/phenoptrExamples/blob/master/inst/extdata/samples/Set12_20-6plex_%5B14146,53503%5D_binary_seg_maps.tif?raw=true',
              path, mode='wb')
img=tiff::readTIFF(path, native=TRUE, all=1)
```

Found on Windows 10 with R 4.1, tiff 0.1-8

**Comment by s-u** [comment]
Thanks, not only that but the result is incorrect, it should be a list but it bailed out early as if `all=FALSE`
