### ISSUE TITLE
Add support for tiled, 32-bit float grayscale

### ISSUE THREAD

**Issue by AB-Kent** [s-u/tiff#4]
Feature request: Add support for tiled, 32-bit float images with `native=FALSE` and `convert=FALSE`.

**Comment by rorynolan** [comment]
Just for peoples information, this functionality exists in the `ijtiff` package which is on CRAN at https://cran.r-project.org/package=ijtiff. Credit to @AB-Kent for the code.

**Comment by s-u** [comment]
Should be now included in c79bc044, thanks to @AB-Kent
