### ISSUE TITLE
Read only a subset of images

### ISSUE THREAD

**Issue by muschellij2** [s-u/tiff#6]
In `readTIFF`, you can either set `all = TRUE` or `all = FALSE`.  Would it be possible to send and index or set of indices to `all`, where only a subset of the images are loaded?  This would be immensely useful for large image stacks.

For example, `imread` in MATLAB has the ability to read a set of files using https://www.mathworks.com/help/matlab/ref/imread.html#btnczv9-1-Index and also a specific region https://www.mathworks.com/help/matlab/ref/imread.html#btnczv9-1-PixelRegion-dup1

**Comment by rorynolan** [comment]
Hi @muschellij2 
The `ijtiff` package (available on CRAN at https://cran.r-project.org/package=ijtiff) has this functionality now in its `read_tif()` function (credit to @AB-kent whose code I used). Does that work for you? If not, is there anything I can do to make `ijtiff` work for you (I am the maintainer).

**Comment by muschellij2** [comment]
Having some issues with the gcc for strex on our cluster https://github.com/rorynolan/strex/issues/3, so I'll have to hold off for a bit on this.

**Comment by rorynolan** [comment]
Just as an FYI for other people reading this, I fixed the issue with `strex` and now @muschellij2 can install `ijtiff` no problem and use it to read only a subset of images.

**Comment by muschellij2** [comment]
Thanks!
