### ISSUE TITLE
install error, tiff.h not found

### ISSUE THREAD

**Issue by tianf8** [s-u/tiff#7]
Tiff could not be installed on linux, I get the following error:
In file included from common.c:1:0: 
common.h:5:18: fatal error: tiff.h: No such file or directory
 #include <tiff.h>                   ^ compilation terminated. 
make: *** [common.o] Error 1 
ERROR: compilation failed for package ‘tiff’ * 
removing ‘/usr/lib64/R/library/tiff’

**Comment by s-u** [comment]
You are missing libtiff development files - you have to install them (on Debian that is `libtiff-dev`).
